  ('/home/runner/work/mlmodels/mlmodels/mlmodels/config/test_config.json',) 
  ('test_all',) 
  ('Running command', 'test_all') 
  ('os.getcwd', '/home/runner/work/mlmodels/mlmodels') 
  ('############Check model ################################',) 
  (['model_tf.temporal_fusion_google', 'model_tf.1_lstm', 'model_sklearn.model_lightgbm', 'model_sklearn.model_sklearn', 'model_tch.pplm', 'model_tch.transformer_sentence', 'model_tch.nbeats', 'model_tch.textcnn', 'model_tch.mlp', 'model_tch.pytorch_vae', 'model_tch.03_nbeats_dataloader', 'model_tch.torchhub', 'model_tch.transformer_classifier', 'model_tch.matchzoo_models', 'model_gluon.gluonts_model', 'model_gluon.fb_prophet', 'model_gluon.gluon_automl', 'model_keras.charcnn', 'model_keras.charcnn_zhang', 'model_keras.namentity_crm_bilstm_dataloader', 'model_keras.01_deepctr', 'model_keras.namentity_crm_bilstm', 'model_keras.nbeats', 'model_keras.textcnn', 'model_keras.keras_gan', 'model_keras.02_cnn', 'model_keras.Autokeras', 'model_keras.armdn', 'model_keras.textvae'],) 
  ('Used', ['model_tf.temporal_fusion_google', 'model_tf.1_lstm', 'model_sklearn.model_lightgbm', 'model_sklearn.model_sklearn', 'model_tch.pplm', 'model_tch.transformer_sentence', 'model_tch.nbeats', 'model_tch.textcnn', 'model_tch.mlp', 'model_tch.pytorch_vae', 'model_tch.03_nbeats_dataloader', 'model_tch.torchhub', 'model_tch.transformer_classifier', 'model_tch.matchzoo_models', 'model_gluon.gluonts_model', 'model_gluon.fb_prophet', 'model_gluon.gluon_automl', 'model_keras.charcnn', 'model_keras.charcnn_zhang', 'model_keras.namentity_crm_bilstm_dataloader', 'model_keras.01_deepctr', 'model_keras.namentity_crm_bilstm', 'model_keras.nbeats', 'model_keras.textcnn', 'model_keras.keras_gan', 'model_keras.02_cnn', 'model_keras.Autokeras', 'model_keras.armdn', 'model_keras.textvae']) 
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tf//temporal_fusion_google') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tf//temporal_fusion_google': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master eb96eb9] ml_store
 1 file changed, 27 insertions(+)
 create mode 100644 log_testall/log_testall_2020-05-07_20-10-43-760.py
To github.com:arita37/mlmodels_store.git
   242ff56..eb96eb9  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tf//1_lstm') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tf//1_lstm': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master fbd4f4f] ml_store
 1 file changed, 25 insertions(+)
To github.com:arita37/mlmodels_store.git
   eb96eb9..fbd4f4f  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_sklearn//model_lightgbm') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_sklearn//model_lightgbm': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master a4fae98] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   fbd4f4f..a4fae98  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_sklearn//model_sklearn') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_sklearn//model_sklearn': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master d75271e] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   a4fae98..d75271e  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//pplm') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//pplm': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master d4d6852] ml_store
 1 file changed, 25 insertions(+)
To github.com:arita37/mlmodels_store.git
   d75271e..d4d6852  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//transformer_sentence') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//transformer_sentence': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master a0b98e9] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   d4d6852..a0b98e9  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//nbeats') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//nbeats': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master e95724e] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   a0b98e9..e95724e  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//textcnn') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//textcnn': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 29c07f3] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   e95724e..29c07f3  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//mlp') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//mlp': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 41d13a6] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   29c07f3..41d13a6  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch.pytorch_vae') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch.pytorch_vae': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 56a652d] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   41d13a6..56a652d  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//03_nbeats_dataloader') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//03_nbeats_dataloader': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 6bc129e] ml_store
 1 file changed, 25 insertions(+)
To github.com:arita37/mlmodels_store.git
   56a652d..6bc129e  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//torchhub') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//torchhub': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 8df8fa2] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
 ! [remote rejected] master -> master (cannot lock ref 'refs/heads/master': is at 7cb149ba0736da757ec1145085d6d5f731224b81 but expected 6bc129e40f475d3f98b422690ab05ef5626c8074)
error: failed to push some refs to 'git@github.com:arita37/mlmodels_store.git'
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//transformer_classifier') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//transformer_classifier': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
From github.com:arita37/mlmodels_store
   6bc129e..7cb149b  master     -> origin/master
Merge made by the 'recursive' strategy.
 log_pullrequest/log_2020-05-07_20-10-36-535.py | 386 +++++++++++++++++++++++++
 1 file changed, 386 insertions(+)
 create mode 100644 log_pullrequest/log_2020-05-07_20-10-36-535.py
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master d42e7d2] ml_store
 1 file changed, 30 insertions(+)
To github.com:arita37/mlmodels_store.git
   7cb149b..d42e7d2  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//matchzoo_models') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//matchzoo_models': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master dad9a30] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   d42e7d2..dad9a30  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_gluon//gluonts_model') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_gluon//gluonts_model': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 886565e] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   dad9a30..886565e  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_gluon//fb_prophet') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_gluon//fb_prophet': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 4d3caf1] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   886565e..4d3caf1  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_gluon//gluon_automl') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_gluon//gluon_automl': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master e897e7a] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   4d3caf1..e897e7a  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//charcnn') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//charcnn': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Warning: Permanently added the RSA host key for IP address '140.82.118.4' to the list of known hosts.
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 9ad1895] ml_store
 1 file changed, 25 insertions(+)
To github.com:arita37/mlmodels_store.git
   e897e7a..9ad1895  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//charcnn_zhang') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//charcnn_zhang': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 21093e6] ml_store
 1 file changed, 25 insertions(+)
To github.com:arita37/mlmodels_store.git
   9ad1895..21093e6  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//namentity_crm_bilstm_dataloader') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//namentity_crm_bilstm_dataloader': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 76a1dad] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   21093e6..76a1dad  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//01_deepctr') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//01_deepctr': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 64e348e] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   76a1dad..64e348e  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//namentity_crm_bilstm') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//namentity_crm_bilstm': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master dd1d124] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   64e348e..dd1d124  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//nbeats') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//nbeats': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 85fff18] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   dd1d124..85fff18  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//textcnn') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//textcnn': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 8981be7] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   85fff18..8981be7  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//keras_gan') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//keras_gan': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 6e9687d] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   8981be7..6e9687d  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//02_cnn') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//02_cnn': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 94476db] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   6e9687d..94476db  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//Autokeras') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//Autokeras': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master c237e16] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   94476db..c237e16  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//armdn') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//armdn': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 524233f] ml_store
 1 file changed, 25 insertions(+)
To github.com:arita37/mlmodels_store.git
   c237e16..524233f  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//textvae') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//textvae': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 82f070a] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   524233f..82f070a  master -> master
