  ('/home/runner/work/mlmodels/mlmodels/mlmodels/config/test_config.json',) 
  ('test_all',) 
  ('Running command', 'test_all') 
  ('os.getcwd', '/home/runner/work/mlmodels/mlmodels') 
  ('############Check model ################################',) 
  (['model_tf.temporal_fusion_google', 'model_tf.1_lstm', 'model_sklearn.model_lightgbm', 'model_sklearn.model_sklearn', 'model_tch.pplm', 'model_tch.transformer_sentence', 'model_tch.nbeats', 'model_tch.textcnn', 'model_tch.mlp', 'model_tch.pytorch_vae', 'model_tch.03_nbeats_dataloader', 'model_tch.torchhub', 'model_tch.transformer_classifier', 'model_tch.matchzoo_models', 'model_gluon.gluonts_model', 'model_gluon.fb_prophet', 'model_gluon.gluon_automl', 'model_keras.charcnn', 'model_keras.charcnn_zhang', 'model_keras.namentity_crm_bilstm_dataloader', 'model_keras.01_deepctr', 'model_keras.namentity_crm_bilstm', 'model_keras.nbeats', 'model_keras.textcnn', 'model_keras.keras_gan', 'model_keras.02_cnn', 'model_keras.Autokeras', 'model_keras.armdn', 'model_keras.textvae'],) 
  ('Used', ['model_tf.temporal_fusion_google', 'model_tf.1_lstm', 'model_sklearn.model_lightgbm', 'model_sklearn.model_sklearn', 'model_tch.pplm', 'model_tch.transformer_sentence', 'model_tch.nbeats', 'model_tch.textcnn', 'model_tch.mlp', 'model_tch.pytorch_vae', 'model_tch.03_nbeats_dataloader', 'model_tch.torchhub', 'model_tch.transformer_classifier', 'model_tch.matchzoo_models', 'model_gluon.gluonts_model', 'model_gluon.fb_prophet', 'model_gluon.gluon_automl', 'model_keras.charcnn', 'model_keras.charcnn_zhang', 'model_keras.namentity_crm_bilstm_dataloader', 'model_keras.01_deepctr', 'model_keras.namentity_crm_bilstm', 'model_keras.nbeats', 'model_keras.textcnn', 'model_keras.keras_gan', 'model_keras.02_cnn', 'model_keras.Autokeras', 'model_keras.armdn', 'model_keras.textvae']) 
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tf//temporal_fusion_google') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tf//temporal_fusion_google': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
From github.com:arita37/mlmodels_store
   fb45f3f..3348520  master     -> origin/master
Updating fb45f3f..3348520
Fast-forward
 log_jupyter/log_2020-05-07_15-59-26-827.py     | 1692 ++++++++++++++++++++++++
 log_pullrequest/log_2020-05-07_16-10-49-975.py |   19 +
 2 files changed, 1711 insertions(+)
 create mode 100644 log_jupyter/log_2020-05-07_15-59-26-827.py
 create mode 100644 log_pullrequest/log_2020-05-07_16-10-49-975.py
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 8fb7d66] ml_store
 1 file changed, 36 insertions(+)
 create mode 100644 log_testall/log_testall_2020-05-07_16-11-00-659.py
To github.com:arita37/mlmodels_store.git
   3348520..8fb7d66  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tf//1_lstm') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tf//1_lstm': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 5f43415] ml_store
 1 file changed, 25 insertions(+)
To github.com:arita37/mlmodels_store.git
   8fb7d66..5f43415  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_sklearn//model_lightgbm') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_sklearn//model_lightgbm': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master b46e36f] ml_store
 1 file changed, 25 insertions(+)
To github.com:arita37/mlmodels_store.git
   5f43415..b46e36f  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_sklearn//model_sklearn') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_sklearn//model_sklearn': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 8ed43a9] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   b46e36f..8ed43a9  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//pplm') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//pplm': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master f71c108] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   8ed43a9..f71c108  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//transformer_sentence') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//transformer_sentence': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master e81e079] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   f71c108..e81e079  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//nbeats') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//nbeats': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 37c55be] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   e81e079..37c55be  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//textcnn') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//textcnn': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 773c523] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   37c55be..773c523  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//mlp') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//mlp': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master cc0346b] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   773c523..cc0346b  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch.pytorch_vae') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch.pytorch_vae': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 3540101] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   cc0346b..3540101  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//03_nbeats_dataloader') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//03_nbeats_dataloader': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 4898bc2] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   3540101..4898bc2  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//torchhub') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//torchhub': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master ca157c5] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   4898bc2..ca157c5  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//transformer_classifier') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//transformer_classifier': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 44a36a1] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   ca157c5..44a36a1  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//matchzoo_models') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tch//matchzoo_models': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 0c2c770] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   44a36a1..0c2c770  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_gluon//gluonts_model') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_gluon//gluonts_model': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 45d213b] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   0c2c770..45d213b  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_gluon//fb_prophet') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_gluon//fb_prophet': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 1407bdc] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   45d213b..1407bdc  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_gluon//gluon_automl') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_gluon//gluon_automl': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 93765c2] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   1407bdc..93765c2  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//charcnn') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//charcnn': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 2647b46] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   93765c2..2647b46  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//charcnn_zhang') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//charcnn_zhang': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Warning: Permanently added the RSA host key for IP address '140.82.112.3' to the list of known hosts.
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 0f5f2f8] ml_store
 1 file changed, 25 insertions(+)
To github.com:arita37/mlmodels_store.git
   2647b46..0f5f2f8  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//namentity_crm_bilstm_dataloader') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//namentity_crm_bilstm_dataloader': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 7fbf3ca] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   0f5f2f8..7fbf3ca  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//01_deepctr') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//01_deepctr': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master fbfcd34] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   7fbf3ca..fbfcd34  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//namentity_crm_bilstm') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//namentity_crm_bilstm': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master cf41146] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   fbfcd34..cf41146  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//nbeats') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//nbeats': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master c1faf8f] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   cf41146..c1faf8f  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//textcnn') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//textcnn': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 7354c4d] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   c1faf8f..7354c4d  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//keras_gan') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//keras_gan': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 73f437b] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   7354c4d..73f437b  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//02_cnn') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//02_cnn': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master b3a5c2d] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   73f437b..b3a5c2d  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//Autokeras') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//Autokeras': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 399ee3e] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   b3a5c2d..399ee3e  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//armdn') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//armdn': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master 9efdfcd] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   399ee3e..9efdfcd  master -> master
  ('\n\n\n', '************', 'python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//textvae') 
python: can't open file '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras//textvae': [Errno 2] No such file or directory
  (' cd /home/runner/work/mlmodels/mlmodels_store/ ;            git config --local user.email "noelkev0@gmail.com" && git config --local user.name "arita37"         ;            git pull --all    ;            ls &&  git add --all &&  git commit -m "ml_store"  ;            git push --all ;            cd /home/runner/work/mlmodels/mlmodels/ ;        ',) 
Fetching origin
Already up to date.
Logs
README.md
README_actions.md
create_error_file.py
create_github_issues.py
error_list
log_benchmark
log_dataloader
log_import
log_json
log_jupyter
log_pullrequest
log_test_cli
log_testall
test_jupyter
[master ce62fa7] ml_store
 1 file changed, 24 insertions(+)
To github.com:arita37/mlmodels_store.git
   9efdfcd..ce62fa7  master -> master
